server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_LINK}
          default-label: main
          skip-ssl-validation: true
          username: atamertokay
          password: ${GIT_JAVA9_KEY}