server:
  port: 9090

spring:
  rabbitmq:
    enabled: false
    host: localhost
    port: 5672
    username: user
    password: user
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/Java9TahminDB
  jpa:
    hibernate:
      ddl-auto: update

authservices:
  secrets:
    secret-key: ${JAVA9_SECRETKEY}
    issuer: ${JAVA9_ISSUER}